name: Release-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Source\Code\CannedBytes.Midi.sln
    - name: Build
      run: dotnet build Source\Code\CannedBytes.Midi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Source\Code\CannedBytes.Midi.sln --no-restore --verbosity normal --filter TestCategory!=LocalOnly
